### ISSUE TITLE
Feature Request: Please add day to day change

### ISSUE THREAD

**Issue by igrinis** [danqing/covid19#28]
Hi,

great visualization. Thanks a lot!!!! Can you add day to day change graph (absolute values), to visualize the speed of epidemic, please?

**Comment by danqing** [comment]
Hi igrinis! What do you mean by day to day change? We have daily cases - is that not what you want?

**Comment by igrinis** [comment]
Yes. I have missed it somehow. Sorry for the trouble. Thanks again!
